# Generated by Django 5.0.6 on 2024-07-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('contact_no', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=100)),
                ('committee', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
    ]
