# Generated by Django 5.1.1 on 2025-02-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(editable=False, max_length=8, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('birthday', models.DateField()),
                ('contact_no', models.CharField(max_length=11)),
                ('image', models.ImageField(blank=True, upload_to='photos/members_photo/')),
                ('location', models.CharField(max_length=100)),
                ('committee', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
    ]
