# Generated by Django 5.1.1 on 2025-08-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
