# Generated by Django 5.1.1 on 2025-08-02 22:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_cloudinary_public_id_member_cloudinary_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cloudinary_public_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cloudinary_url',
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
