# Generated by Django 5.0.6 on 2024-08-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_no',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
