# Generated by Django 5.0.6 on 2024-08-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('date_visited', models.DateTimeField(auto_now_add=True)),
                ('contact_no', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
