# Generated by Django 5.1.1 on 2025-06-29 20:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tithe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_given', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money')], default='cash', max_length=20)),
                ('contribution_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('donation', 'Donation'), ('building', 'Building Fund'), ('mission', 'Missions'), ('other', 'Other')], default='tithe', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tithes', to='member.member', to_field='member_no', verbose_name='Member')),
                ('recorded_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_tithes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tithe Record',
                'verbose_name_plural': 'Tithe Records',
                'ordering': ['-date_given'],
            },
        ),
    ]
