# Generated by Django 5.1.1 on 2025-06-29 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('tithe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithe',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tithes', to='member.member', verbose_name='Member'),
        ),
    ]
