# Generated by Django 5.1.1 on 2025-06-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tithe', '0002_alter_tithe_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='tithe',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tithe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
